title: ""
baseurl: "/Covid-19-Reference-Library"
collections_dir: content
exclude: [loader]

collections:
  data_elements:
    output: false
  datasets:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "data_elements"
    values:
      layout: "data_element"
  -
    scope:
      path: ""
      type: "datasets"
    values:
      layout: "first_letter"
